# Generated by Django 5.2.1 on 2025-05-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('teor_alcool', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('hora', models.DateTimeField()),
                ('preco_J', models.FloatField()),
                ('preco_S', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=820)),
            ],
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_budies.evento')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_budies.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='beer_budies.universidade'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bebidas', models.IntegerField(default=0)),
                ('total_festas', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('data_entrada', models.DateField()),
                ('classificacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beer_budies.classificacao')),
                ('eventos', models.ManyToManyField(through='beer_budies.ParticipaEvento', to='beer_budies.evento')),
                ('grupos', models.ManyToManyField(through='beer_budies.ParticipaGrupo', to='beer_budies.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='participagrupo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_budies.user'),
        ),
        migrations.AddField(
            model_name='participaevento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_budies.user'),
        ),
        migrations.CreateModel(
            name='UserBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('coordenadas', models.CharField(max_length=50)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_budies.bebida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_budies.user')),
            ],
        ),
    ]
