# Generated by Django 5.2.1 on 2025-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_budies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='num_membros',
            field=models.IntegerField(default=0),
        ),
    ]
