# Generated by Django 5.2.1 on 2025-05-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_budies', '0003_remove_evento_universidade_remove_evento_preco_s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbebida',
            name='bebida',
        ),
        migrations.RemoveField(
            model_name='participaevento',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='participaevento',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eventos',
        ),
        migrations.RemoveField(
            model_name='participagrupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='participagrupo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='userbebida',
            name='user',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('total_bebidas', models.IntegerField(default=0)),
                ('total_festas', models.IntegerField(default=0)),
                ('data_entrada', models.DateField()),
                ('classificacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beer_budies.classificacao')),
            ],
        ),
        migrations.DeleteModel(
            name='Bebida',
        ),
        migrations.DeleteModel(
            name='ParticipaEvento',
        ),
        migrations.DeleteModel(
            name='ParticipaGrupo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserBebida',
        ),
    ]
