# Generated by Django 5.2 on 2025-05-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_budies', '0004_remove_userbebida_bebida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('teor_alcool', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('coordenadas', models.CharField(max_length=50)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_budies.bebida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_budies.userinfo')),
            ],
        ),
    ]
