# Generated by Django 5.2.1 on 2025-05-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_budies', '0004_remove_userbebida_bebida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='data_entrada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
