# Generated by Django 5.2.1 on 2025-05-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_budies', '0006_remove_userinfo_username_userinfo_user'),
        ('beer_budies', '0007_userbebida_cervejas_userbebida_evento_and_more'),
    ]

    operations = [
    ]
