# Generated by Django 5.2.1 on 2025-05-19 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_budies', '0009_remove_userinfo_username_alter_userinfo_data_entrada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='membros',
            field=models.ManyToManyField(related_name='grupos', to=settings.AUTH_USER_MODEL),
        ),
    ]
